In [ ]:
# THE KNAPSACK PROBLEM
import numpy as np

#INPUT VALUES
values = (3, 4, 5, 6)
weight = (2, 3, 4, 5)
maxWeight = 5

numberOfElements = len(values)

#CALCULATING VALUES USING DYNAMIC PROGRAMMING

#We're using a matrix rows = currElement and col = currWeight
DP = np.zeros((numberOfElements + 1, maxWeight + 1))

#In cpp for(int currElement = 1; currElement < numberOfElements + 1; currElement++)
for currElement in range(1, numberOfElements + 1): 
  #In cpp for(int currWeight = 1; currWeight < maxWeight + 1; currWeight++)
  for currWeight in range(1, maxWeight + 1):
    #Current element weight is greater than current weight (impossible to add)
    if weight[currElement - 1] > currWeight:
      DP[currElement][currWeight] = DP[currElement - 1][currWeight]
    else:
      #Transition list: as a summary the decisions that we can take to choose what's better at this point 
      notTakeCurrentElement = DP[currElement - 1][currWeight]
      takeCurrentElement = DP[currElement - 1][currWeight - weight[currElement - 1]] + values[currElement - 1]
      DP[currElement][currWeight] = max(notTakeCurrentElement, takeCurrentElement)
    
print(f'Table result:\n{DP}')

#DP RECONSTRUCTION we can get the elements of the best solution
elementsUsed = []
itemValues = []
itemWeights = []


while currElement >= 0 and currWeight >= 0:
  #We move from bottom to up until the current element is different to the previous element
  while currElement > 0 and DP[currElement][currWeight] == DP[currElement - 1][currWeight]:
    currElement -= 1
  if currElement > 0:
    #If the current element is different to the previous one (with the same weight) we find an element that is part of the answer
    elementsUsed.append(currElement)
    itemValues.append(values[currElement - 1])
    itemWeights.append(weight[currElement - 1])
  currWeight -= (weight[currElement - 1])
  currElement -= 1

elementsUsed.reverse()
itemValues.reverse()
itemWeights.reverse()

print(f'\nThe best solution with a maximum weight of: {maxWeight} is: {DP[numberOfElements][maxWeight]} \nthe elements used were: {elementsUsed} (in that specific order) \nit means the items with values: {itemValues} and weights {itemWeights} respectively')


Table result:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 3. 3. 3.]
 [0. 0. 3. 4. 4. 7.]
 [0. 0. 3. 4. 5. 7.]
 [0. 0. 3. 4. 5. 7.]]

The best solution with a maximum weight of: 5 is: 7.0 
the elements used were: [1, 2] (in that specific order) 
it means the items with values: [3, 4] and weights [2, 3] respectively


In [ ]:
!python --version

Python 3.7.12


In [ ]:
# COIN CHANGE PROBLEM GREEDY VERSION

import numpy as np

# INPUT VALUES

coins = (1, 2, 5)
value = 6

solution = {}

for denomination in coins:
  solution[denomination] = 0

currentValue = 0
currElement = len(coins) - 1

while currentValue < value:
  if(value - currentValue) >= coins[currElement]:
    currentValue += coins[currElement]
    solution[coins[currElement]] += 1
  else:
    currElement -= 1

print("The solution is to use", sum(solution.values()), "coins")
for denomination in coins:
    print(solution[denomination],"coins of denomination", denomination)

Coin selected: 5
Coin selected: 1
The solution is to use 2 coins
1 coins of denomination 1
0 coins of denomination 2
1 coins of denomination 5


In [ ]:
#DYNAMIC PROGRAMMING

import numpy as np

coins = [1, 2, 5]
value = 11

nCoins = len(coins)

#currCoins = our coins and currValues = values (it starts from zero)
DP = np.zeros((nCoins, value + 1))

#for(currValue = 1; currValue < value + 1; currValue++)
for currValue in range(1, value + 1):
  DP[0][currValue] = currValue

for currCoin in range(1, nCoins):
  for currValue in range(1, value + 1):
    #Current coin value is impossible to use it because it's value is greater than the current change
    if coins[currCoin] > currValue:
      #We store the best solution at this point ignoring the current coin but using the previous one
      DP[currCoin][currValue] = DP[currCoin - 1][currValue]
    else:
      #We can use the current coin but also we can check if with the previous coin but with the same change we have a better solution
      #Transition list:
      notTakeCurrentCoin = DP[currCoin - 1][currValue]
      takeCurrentCoin = DP[currCoin][currValue - coins[currCoin]] + 1
      DP[currCoin][currValue] = min(notTakeCurrentCoin, takeCurrentCoin)
        
print(f'Table result: \n{DP}')

coinsUsed = []
coinsValues = []

while currCoin >= 0:
  while currValue >= 0:
    if DP[currCoin][currValue] != DP[currCoin - 1][currValue] and coins[currCoin] <= value:
      currValue -= coins[currCoin]
      coinsUsed.append(currCoin)
      coinsValues.append(coins[currCoin])
    elif currCoin == 0 and coins[currCoin] <= currValue:
      currValue -= coins[currCoin]
      coinsUsed.append(currCoin)
      coinsValues.append(coins[currCoin])
    else:
      currCoin -= 1
      break

print(f'With the change: {value} we need to use: {DP[nCoins - 1][value]} to minimize the number of coins, \nand the coins to use are: {coinsUsed} with the values {coinsValues}')

Table result: 
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 0.  1.  1.  2.  2.  3.  3.  4.  4.  5.  5.  6.]
 [ 0.  1.  1.  2.  2.  1.  2.  2.  3.  3.  2.  3.]]
With the change: 11 we need to use: 3.0 to minimize the number of coins, 
and the coins to use are: [2, 2, 0] with the values [5, 5, 1]


In [ ]:
#DYNAMIC PROGRAMMING

import numpy as np

def areEqualCharacters(a, b):
  return 0 if a == b else 1

firstWord = "hello"
secondWord = "hallo"

maxFirstWord = len(firstWord)
maxSecondWord = len(secondWord)

DP = np.zeros((maxFirstWord + 1, maxSecondWord + 1))

#It is equals to for(int i = 0; i < firstWord + 1; i++)
for i in range(maxFirstWord + 1):
  #This case means the secondWord is empty so we do not need to change anything
  DP[i][0] = i

#It is equals to for(int j = 0; j < secondWord + 1; j++)
for j in range(maxSecondWord + 1):
  #Very similar to the previous case it means firstWord is empty we do not need to change anything
  DP[0][j] = j

for i in range(1, maxFirstWord + 1):
  for j in range(1, maxSecondWord + 1):
    #Trivial solution, one of the strings is empty in this subproblem
    if min(i, j) == 0:
      DP[i][j] = max(i, j)
    #Transition list
    #Fist transition: we move the first pointer
    moveFirstPointer = DP[i - 1][j] + 1
    #Second transition: we move the second pointer
    moveSecondPointer = DP[i][j - 1] + 1
    #third transition: we move both pointers and we check if both characters are equal or not (if they are equal we add 1 to the solution)
    moveBothPointers = DP[i - 1][j - 1] + areEqualCharacters(firstWord[i - 1], secondWord[j - 1])
    #We choose the best solution
    DP[i][j] = min(moveFirstPointer, moveSecondPointer, moveBothPointers)

print(f'Table result: \n{DP}')
print(f'\nMinimum moves needed: {DP[maxFirstWord][maxSecondWord]} with the words "{firstWord}" and "{secondWord}"')

Table result: 
[[0. 1. 2. 3. 4. 5.]
 [1. 0. 1. 2. 3. 4.]
 [2. 1. 1. 2. 3. 4.]
 [3. 2. 2. 1. 2. 3.]
 [4. 3. 3. 2. 1. 2.]
 [5. 4. 4. 3. 2. 1.]]

Minimum moves needed: 1.0 with the words "hello" and "hallo"
